flags: {}
packages:
- '.'
# - /j/Projects/BaseOh/.stack-work/dist/2672c1f3/BaseOh-0.1.0.0.tar.gz
# - location:
#     git: git@github.com:nionita/BaseOh.git
#     commit: 02a4597df417be6ad41e74441e29a79d77c664f5
extra-deps: []
resolver: lts-4.2
